

name: Deploy DotNet project to Azure WebApp

on:
  push:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: 'SRPM'  # set this to your web app name on Azure
  AZURE_WEBAPP_PACKAGE_PATH: './SRPM/SRPM_APIServices/publish'       # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-deploy:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
    # - name: 'Login via Azure CLI'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: 'Build .NET Project'
      shell: pwsh
      run: |
        dotnet build ./SRPM/SRPM_APIServices/SRPM_APIServices.csproj --configuration Release
    - name: 'Clean publish folder'
      run: |
        if (Test-Path "./SRPM/SRPM_APIServices/publish") { Remove-Item -Recurse -Force "./SRPM/SRPM_APIServices/publish" }
    - name: 'Publish .NET Project'
      shell: pwsh
      run: |
        dotnet publish ./SRPM/SRPM_APIServices/SRPM_APIServices.csproj --configuration Release --output ./SRPM/SRPM_APIServices/publish

    - name: 'Run Azure Deploy Action'
      uses: Azure/webapps-deploy@v2
      id: fa
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./SRPM/SRPM_APIServices/publish
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
